test
gist-helper/helperSpringV2 pull request #27
Opened 2023-02-22 17:03 UTC by leeyeaeun

곧밥 기능에 1학 1층과 2층을 추가했습니다.

2023-02-23 03:59 UTC, kimtks456 requested changes
확인부탁드려요!

2023-02-23 03:59 UTC, kimtks456 commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        if(result0.isEmpty()|| result1.isEmpty()||result2.isEmpty()) {
|| 이면 주말의 경우, result0,1이 empty니까 2학이 있어도 2학 메뉴가 들어가지 않고, NO_MEAL_KOR가 반환될 것 같습니다

&&으로 묶어서 셋 다 비어있는날(ex 명절)이면 NO_MEAL 반환하는게 나을 듯 합니다

2023-02-23 03:59 UTC, kimtks456 commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal2.generateMenu()
meal2 -> meal0 이 되어야 하지 않을까 싶습니다

2023-02-23 04:50 UTC, HoyoenKim commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal2.generateMenu()
주말에만 식단을 추가하는 걸로 보이는데요

1학에는 주말이 없어서 넘어가고 (meal0, meal1) 2학만 넣어주는것 (meal2) 아닐까요?

2023-02-23 04:52 UTC, HoyoenKim commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal2.generateMenu()
별개로 이 함수가 제대로 동작하는지 테스트는 필요해 보이네요

2023-02-23 04:53 UTC, HoyoenKim commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal2.generateMenu()
> meal2 -> meal0 이 되어야 하지 않을까 싶습니다

line 100

2023-02-24 03:22 UTC, leeyeaeun commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        if(result0.isEmpty()|| result1.isEmpty()||result2.isEmpty()) {
헉!! 그렇네요 수정하겠습니다

2023-02-24 03:52 UTC, closed without merging