Soon menu1
gist-helper/helperSpringV2 pull request #29
Opened 2023-02-24 06:38 UTC by leeyeaeun

곧밥 기능에 1학과 2학을 추가했습니다.

2023-02-24 07:06 UTC, kimtks456 commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal1.generateMenu() + "\n-------------------\n" + meal2.generateMenu();
평일 아침, 저녁이면 1학 1층 + 2학이니 `meal0 + meal2` 이렇게 되어야하지 않을까 싶습니다!

2023-02-24 07:09 UTC, kimtks456 requested changes
이부분만 바꾸고 local에서 곧밥 response 받아서 해당 json 파일의 menu 부분들 print 해보면 잘 된건지 안된건지 확인해볼 수 있을 것 같아요! print한 결과 확인해보시고 이상없으시면 말씀해주세요~~

2023-02-24 07:24 UTC, leeyeaeun commented on src/main/java/com/example/helper/service/ChatbotService.java
> +                result += meal1.generateMenu() + "\n-------------------\n" + meal2.generateMenu();
헐 이런 실수를.. 바로 수정하겠습니다!!

2023-02-24 10:35 UTC, HoyoenKim requested changes
result0, 1, 2 에서 meal0, 1, 2 를 get으로 가져오는 부분 (ChatbotService line 85 - 88) 에서 에러가 발생하는 것 같습니다.

식단이 비어 있고 정상 동작을 한다면 "식단 준비중입니다" 와 같은 response가 발생합니다.

테스트 시 text 에 빈 스트링이 포함되어 있다면, result.get()  (ChatbotService line 85 - 88) 부분에서 500 internal error 가 의심되네요.

확인 후 수정 부탁드립니다.

2023-02-24 10:35 UTC, HoyoenKim commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        Meal meal0 = result0.get();
result0 가 empty 가 아닌 경우에만 Meal meal0 = result0.get() 으로 가져올 수 있습니다. 나머지 1, 2도 마찬가지입니다. 

result.empty() 를 체크하는 method를 만들고 여기서 empty 가 아닌 경우에만 get 으로 가져오는 걸로 해야 될 것 같습니다.

2023-02-24 10:35 UTC, HoyoenKim commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        if(meal2.getDateType().equals(Types.DATE_SAT.getType()) || meal2.getDateType().equals(Types.DATE_SUN.getType())){
meal2 에서 date를 가져오는 아이디어는 좋은데요, 만약 meal2 가 empty 인 경우에는 동작하지 않을 것 같습니다.

Spring 의 Date 객체를 이용하여 곧밥 식단의 시점의 Date를 계산해 토 / 일 그리고 점심을 체크하는 방식으로 바꾸면 좋을 것 같습니다.

2023-02-24 14:37 UTC, leeyeaeun commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        Meal meal0 = result0.get();
맞아요 계속 get()에서 500에러가 떴었습니다, 근데 신기하게 meal1만 에러를 떠서 exist함수를 써봤었는데... 그래도 똑같이 아무런 text가 나오지 않더라구요. 제가 함수를 잘못 이해하고 있었던 것같습니다. 말씀하신 방법대로 해결했습니다!

2023-02-24 14:38 UTC, leeyeaeun commented on src/main/java/com/example/helper/service/ChatbotService.java
> +        if(meal2.getDateType().equals(Types.DATE_SAT.getType()) || meal2.getDateType().equals(Types.DATE_SUN.getType())){
네!! 좋은 의견 감사합니다. 말씀하신 대로 Date 객체를 사용하는 것으로 수정했습니다.

2023-02-25 03:08 UTC, HoyoenKim approved these changes
고생하셨어요~ 월요일에 리뷰 부탁드립니다.

2023-02-27 08:22 UTC, kimtks456 approved these changes

2023-02-27 08:22 UTC, merged